apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: ${SPOKE_NS}-flux-operator
spec:
# rollbackLimit: 3
  forProvider:
    chart:
      name: flux-operator
      repository: "oci://ghcr.io/controlplaneio-fluxcd/charts"
      version: 0.23.0
    namespace: flux-system
  providerConfigRef:
    name: ${SPOKE_NS}-helm-provider