apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: ${SPOKE_NS}-flux-operator
spec:
  forProvider:
    chart:
      name: flux-operator
      repository: "oci://ghcr.io/controlplaneio-fluxcd/charts"
      version: 0.23.0
    namespace: flux-system
  providerConfigRef:
    name: ${SPOKE_NS}-helm-provider
---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: ${SPOKE_NS}-flux-instance
spec:
  forProvider:
    chart:
      name: flux-instance
      repository: "oci://ghcr.io/controlplaneio-fluxcd/charts"
      version: 0.23.0
    namespace: flux-system
    values:
      instance:
        distribution:
          version: "2.x"
          registry: "ghcr.io/fluxcd"
        sync:
          kind: GitRepository
          url: ${GIT_URL}
          path: ${FLUX_PATH}
          ref: ${GIT_REF}
  providerConfigRef:
    name: ${SPOKE_NS}-helm-provider