apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
spec: {}
status: {}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-operator-spoke-helm-repo
  namespace: flux-system
spec:
  interval: 5m0s
  url: "oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator"
  ref:
    semver: ">= 0.23"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator-spoke-helm-release
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: flux-operator-spoke-helm-repo
    namespace: ${BUSINESS_NS}
  interval: 10m
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-instance-spoke-helm-repo
  namespace: flux-system
spec:
  interval: 5m0s
  url: "oci://ghcr.io/controlplaneio-fluxcd/charts/flux-instance"
  ref:
    semver: ">= 0.23"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-instance-spoke-helm-release
  namespace: flux-system
spec:
  dependsOn:
  - name: flux-operator-spoke-helm-release
    namespace: flux-system
  chartRef:
    kind: OCIRepository
    name: flux-instance-spoke-helm-repo
    namespace: flux-system
  interval: 10m
  values:
    instance:
      distribution:
        version: "2.x"
        registry: "ghcr.io/fluxcd"
      sync:
        kind: GitRepository
        url: ${GIT_URL}
        path: ${FLUX_PATH}
        ref: ${GIT_REF}
  