apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
spec: {}
status: {}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flux-operator-spoke-helm-repo
  namespace: flux-system
spec:
  type: "oci"
  interval: 5m0s
  url: "oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator-spoke-helm-release
  namespace: flux-system
spec:
  chartRef:
    kind: HelmRepository
    name: flux-operator-spoke-helm-repo
    namespace: flux-system
  interval: 5m