apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flux-operator-spoke-helm-repo
  namespace: flux-system
spec:
  type: "oci"
  interval: 5m0s
  url: "oci://ghcr.io/controlplaneio-fluxcd/charts"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator-spoke-helm-release
  namespace: ${SPOKE_NS}
spec:
  targetNamespace: admin
  storageNamespace: admin
  releaseName: admin
  serviceAccountName: flux-admin
  chart:
    spec:
      chart: flux-operator
      sourceRef:
        kind: HelmRepository
        name: flux-operator-spoke-helm-repo
        namespace: flux-system
  interval: 1m
  kubeConfig:
    secretRef:
      name: cluster-kubeconfig
      key: value