apiVersion: bancolombia.businessflows/v1
kind: Micro
metadata:
  namespace: default
  name: micro-prueba
spec:
  image: nginx
  replicas: 1
  aws-resources:
    region: us-east-1
    db-name: example
