---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: crossplane-helm-repo
  namespace: crossplane-system
spec:
  interval: 5m0s
  url: https://charts.crossplane.io/preview