apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
spec: {}
status: {}
--- 
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: crossplane-helm-repo
  namespace: crossplane-system
spec:
  interval: 5m0s
  url: https://charts.crossplane.io/preview
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane-helm-release
  namespace: crossplane-system
spec:
  interval: 10m
  chart:
    spec:
      chart: crossplane
      version: v2.0.0-preview.1
      sourceRef:
        kind: HelmRepository
        name: crossplane-helm-repo
        namespace: crossplane-system
      interval: 10m
      values:
        provider:
          packages:
          - xpkg.upbound.io/upbound/provider-kubernetes:v0.16.0