apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane-release
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: crossplane
      version: v2.0.0-preview.1
      sourceRef:
        kind: HelmRepository
        name: crossplane-helm-repo
        namespace: flux-system
      interval: 10m