apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: ${SPOKE_NS}-helm-provider
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: ${SPOKE_NS}
      name: cluster-kubeconfig
      key: value