apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: ${SPOKE_NS}-crossplane
spec:
  forProvider:
    chart:
      name: flux-instance
      repository: "https://charts.crossplane.io/preview"
      version: v2.0.0-preview.1
    namespace: crossplane-system
    values: 
      provider:
        packages: ${packages}
  providerConfigRef:
    name: ${SPOKE_NS}-helm-provider