apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: ${CLUSTER-NS}-admin-ns
  annotations:
    uptest.upbound.io/timeout: "60"
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: admin
        labels:
          example: "true"
  providerConfigRef:
    name: ${CLUSTER-NS}-kubernetes-provider
---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: ${CLUSTER-NS}-admin-sa
  annotations:
    uptest.upbound.io/timeout: "60"
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: flux-admin
        namespace: admin
  providerConfigRef:
    name: ${CLUSTER-NS}-kubernetes-provider
---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: ${CLUSTER-NS}-admin-rolebinding
  annotations:
    uptest.upbound.io/timeout: "60"
spec:
  forProvider:
    manifest:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: flux-admin-rolebinding
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        name: flux-admin
        namespace: admin
  providerConfigRef:
    name: ${CLUSTER-NS}-kubernetes-provider