apiVersion: v1
kind: Namespace
metadata:
  name: admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-admin
  namespace: admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-admin-rolebinding-${CLUSTER_NS}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: flux-admin
  namespace: admin