apiVersion: rds.aws.upbound.io/v1beta3
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rds/v1beta3/instance
  labels:
    testing.upbound.io/example-name: example-dbinstance
  name: example-dbinstance
spec:
  providerConfigRef:
    name: aws-config
  forProvider:
    passwordSecretRef:
      name: db-manager-password
      key: pass
      namespace: default
    allocatedStorage: 20
    autoGeneratePassword: true
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 14
    backupWindow: 09:46-10:16
    dbName: example
    engine: postgres
    engineVersion: "16.6"
    instanceClass: db.t3.micro
    maintenanceWindow: Mon:00:00-Mon:03:00
    publiclyAccessible: false
    region: us-east-1
    skipFinalSnapshot: true
    storageEncrypted: true
    storageType: gp2
    username: adminuser
  writeConnectionSecretToRef:
    name: db-creds
    namespace: manager-cluster
