apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: spoke-management
  namespace: cuentas-cluster
spec:
  targetNamespace: cuentas-cluster
  interval: 1h
  retryInterval: 3m
  timeout: 5m
  prune: true
  wait: true
  path: ./config/kubernetes/spokes/.businessflow-repo
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      SPOKE_NS: cuentas-cluster
      GIT_URL: "https://github.com/jdarguello/CDT_Businessflow"
      GIT_REF: "main"
      FLUX_PATH: "./infra/gitops"