apiVersion: batch/v1
kind: CronJob
metadata:
  name: refresh-cluster-kubeconfig-secret
  namespace: ${SPOKE_NS}
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: flux-admin
          restartPolicy: OnFailure
          containers:
          - name: refresh
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - |
              NEW_TOKEN=$(kubectl create token flux-admin -n ${SPOKE_NS})
              USER="flux-admin"
              CONTEXT="flux-admin@kubernetes"

              kubectl get secret cluster-kubeconfig -n ${SPOKE_NS} \
                -o jsonpath='{.data.value}' | base64 -d \
              | jq --arg tok "$NEW_TOKEN" '.users[0].user.token = $tok' \
              | jq --arg user "$USER" '.users[0].name = $user' \
              | jq --arg user "$USER" '.contexts[0].context.user = $user' \
              | jq --arg context "$CONTEXT" '.contexts[0].name = $context' \
              | kubectl create secret generic cluster-kubeconfig -n ${SPOKE_NS} \
                  --from-file=value=/dev/stdin \
                  --dry-run=client -o yaml \
              | kubectl apply -f -
