apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-admin
  namespace: inversiones-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: inversiones-cluster
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podran-repo
  namespace: inversiones-cluster
spec:
  interval: 1m
  url: https://github.com/stefanprodan/podinfo
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podran-ks
  namespace: inversiones-cluster
spec:
  targetNamespace: default
  interval: 1h
  retryInterval: 3m
  timeout: 5m
  prune: true
  wait: true
  path: ./kustomize
  serviceAccountName: default
  sourceRef:
    kind: GitRepository
    name: podran-repo
    namespace: inversiones-cluster
  kubeConfig:
    secretRef:
      name: cluster-kubeconfig