apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-setup
  namespace: inversiones-cluster
spec:
  targetNamespace: inversiones-cluster
  interval: 1h
  retryInterval: 3m
  timeout: 5m
  prune: true
  wait: true
  path: ./config/kubernetes/spokes/.cloud-native/crossplane
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      SPOKE_NS: inversiones-cluster
      CROSSPLANE_PACKAGES:
      - xpkg.crossplane.io/crossplane-contrib/provider-aws:v0.39.0
      - xpkg.upbound.io/crossplane-contrib/provider-sql:v0.9.0