apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: inversion-flux
  namespace: inversiones-cluster
spec:
  targetNamespace: inversiones-cluster
  interval: 2m
  retryInterval: 1m
  timeout: 3m
  prune: true
  wait: true
  path: ./config/kubernetes/spokes/.cloud-native/flux
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      SPOKE_NS: inversiones-cluster