apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: inversion-flux
  namespace: admin
spec:
  targetNamespace: inversiones-cluster
  interval: 1h
  retryInterval: 3m
  timeout: 5m
  prune: true
  wait: true
  path: ./config/kubernetes/spokes/.cloud-native/flux
  serviceAccountName: "flux-admin"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      GIT_URL: "https://github.com/jdarguello/CDT_Businessflow"
      GIT_REF: "refs/heads/main"
      FLUX_PATH: "infra/gitops"
  #kubeConfig:
  #  secretRef:
  #    name: cluster-kubeconfig
  #    namespace: inversiones-cluster
  patches:
    - target:
        kind: HelmRelease
      patch: |
        - op: add
          path: /spec/kubeConfig
          value:
            secretRef:
              name: cluster-kubeconfig
              namespace: inversiones-cluster