apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeconfig-renewal
  namespace: ${SPOKE_NS}
spec:
  dependsOn:
  - name: crossplane-provider-setup
  targetNamespace: ${SPOKE_NS}
  interval: 1h
  retryInterval: 3m
  timeout: 5m
  prune: true
  wait: true
  path: ./config/kubernetes/spokes/.config/spoke-kubeconfig
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      SPOKE_NS: ${SPOKE_NS}