apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-operator-setup
  namespace: ${SPOKE_NS}
spec:
  targetNamespace: ${SPOKE_NS}
  interval: 1h
  retryInterval: 3m
  timeout: 5m
  prune: true
  wait: true
  path: ./config/kubernetes/spokes/.cloud-native/flux
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      SPOKE_NS: ${SPOKE_NS}
      GIT_URL: ${GIT_URL}
      GIT_REF: ${GIT_REF}
      FLUX_PATH: ${FLUX_PATH}