apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-provider-setup
  namespace: ${SPOKE_NS}
spec:
  targetNamespace: ${SPOKE_NS}
  interval: 1h
  retryInterval: 3m
  timeout: 5m
  prune: true
  wait: true
  path: ./config/kubernetes/manager/flux-management/crossplane-providers/kubernetes
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      CLUSTER_NS: ${SPOKE_NS}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-rbac-setup
  namespace: ${SPOKE_NS}
spec:
  dependsOn:
  - name: crossplane-provider-setup
  targetNamespace: ${SPOKE_NS}
  interval: 1h
  retryInterval: 3m
  timeout: 5m
  prune: true
  wait: true
  path: ./config/kubernetes/spokes/.cloud-native/rbac
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      CLUSTER_NS: ${SPOKE_NS}