apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ex
  name: ex
  namespace: default
spec:
  containers:
  - image: nginx
    name: ex
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
