apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hub-manager-platform-engineering
  namespace: ${SPOKE_NS}
spec:
  interval: 1h
  retryInterval: 3m
  timeout: 5m
  prune: true
  wait: true
  path: ./config/platform-engineering
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      SPOKE_NS: ${SPOKE_NS}
  kubeConfig:
    secretRef:
      name: cluster-kubeconfig
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hub-manager-seguridad
  namespace: ${SPOKE_NS}
spec:
  targetNamespace: ${SPOKE_NS}
  interval: 1h
  retryInterval: 3m
  timeout: 5m
  prune: true
  wait: true
  path: ./config/seguridad
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  kubeConfig:
    secretRef:
      name: cluster-kubeconfig