---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: manager-repo
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/jdarguello/CloudManager
  ref:
    branch: main