name: manager-setup
description: Levanta el Manager-Cluster y establece configuraciones base en este

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        working-directory: platform-engineering/CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" > .env
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
          echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> .env
      
      - name: Install and init Devbox
        uses: jetpack-io/devbox-install-action@v0.13.0
        with:
          enable-cache: 'true'
          project-path: platform-engineering/CLI
          devbox-version: 0.15.1
      
      