name: new-backdb
description: Define y configura un nuevo microservicio vinculado al flujo de negocio

on:
  workflow_dispatch:
    inputs:
      businessflow_name:
        required: true
        description: Nombre del flujo de negocio
      micro_name:
        description: Nombre del microservicio
      image: 
        required: true
        description: Imagen base de los contenedores
      back_name:
        required: true
        description: Nombre base del backend (inclye BD)
      replicas: 
        required: true
        description: Numero de replicas
      new_micro_repo:
        required: true
        description: Define si crea o no un nuevo repositorio para el microservicio
        

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.TOKEN_GITHUB }}
          fetch-depth: 0

      - name: Create .env file
        working-directory: platform-engineering/CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" > .env
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
          echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> .env
      
      - name: Install and init Devbox
        uses: jetpack-io/devbox-install-action@v0.13.0
        with:
          enable-cache: 'true'
          refresh-cli:  'true'
          devbox-version: 0.15.0
          project-path: 'platform-engineering/CLI'
      
      - name: Define new businessflow
        working-directory: platform-engineering/CLI
        run: |
          devbox run bancli service back-db new \
            --businessflow-name="${{ github.event.inputs.businessflow_name }}" \
            --micro-name="${{ github.event.inputs.micro_name }}" \
            --image="${{ github.event.inputs.image }}" \
            --back-name="${{ github.event.inputs.back_name }}" \
            --replicas="${{ github.event.inputs.replicas }}" \
            --new-micro-repo="${{ github.event.inputs.new_micro_repo }}"